#!/usr/bin/env node
/**
 * Regenerates src/lib/emojiData.ts — the chat emoji picker's whole dataset.
 *
 * WHY THIS IS A BUILD-TIME SCRIPT AND NOT A RUNTIME FETCH: the chat widget
 * (vue-advanced-chat) ships emoji-picker-element, which pulls this exact JSON
 * from jsdelivr the first time somebody opens the picker. On the live site
 * that request is blocked outright — netlify.toml's `connect-src` does not
 * list the CDN — so the picker only ever said "Could not load emoji." A
 * canvasser on one bar of signal shouldn't be waiting on a CDN to send 👍
 * either. Downloading it here and committing the result means the picker
 * costs zero requests and works with the phone in airplane mode.
 *
 * Source: emojibase (MIT), via the emoji-picker-element-data package.
 *
 *   node scripts/fetch-emoji.mjs
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const SOURCE = 'https://cdn.jsdelivr.net/npm/emoji-picker-element-data@^1/en/emojibase/data.json'
const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'lib', 'emojiData.ts')

/**
 * Emoji newer than this render as an empty tofu box on phones that shipped
 * before it, and a picker full of blanks is worse than a shorter picker.
 * Unicode 14 is 2021 — iOS 15.4 and Android 12, which is everything a
 * volunteer is plausibly carrying.
 */
const MAX_UNICODE_VERSION = 14

/**
 * CLDR group ids, in the order they appear here. Group 2 (Component: bare
 * skin-tone and hair modifiers) is deliberately absent — those aren't emoji
 * anyone sends on their own.
 */
const GROUPS = [
  [0, 'Smileys'],
  [1, 'People'],
  [3, 'Animals & nature'],
  [4, 'Food & drink'],
  [5, 'Travel & places'],
  [6, 'Activities'],
  [7, 'Objects'],
  [8, 'Symbols'],
  [9, 'Flags'],
]

/** Words already in the name are dead weight in the search blob. */
function extraTerms(entry) {
  const inName = new Set(entry.annotation.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean))
  const terms = new Set()
  for (const raw of [...(entry.tags ?? []), ...(entry.shortcodes ?? [])]) {
    for (const word of String(raw).toLowerCase().split(/[^a-z0-9]+/)) {
      if (word && !inName.has(word)) terms.add(word)
    }
  }
  return [...terms].sort().join(' ')
}

const res = await fetch(SOURCE)
if (!res.ok) throw new Error(`${SOURCE} -> HTTP ${res.status}`)
const all = await res.json()

const byGroup = new Map(GROUPS.map(([id]) => [id, []]))
let skippedNew = 0
for (const entry of all) {
  const bucket = byGroup.get(entry.group)
  if (!bucket) continue
  if (Number(entry.version) > MAX_UNICODE_VERSION) {
    skippedNew++
    continue
  }
  // Base emoji only. The `skins` array holds the toned variants; the picker
  // offers no tone control, same call the avatar set made.
  bucket.push({ char: entry.emoji, name: entry.annotation, terms: extraTerms(entry), order: entry.order ?? 0 })
}

const q = (s) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`

let total = 0
const groupSrc = GROUPS.map(([id, label]) => {
  const rows = byGroup.get(id).sort((a, b) => a.order - b.order)
  total += rows.length
  const items = rows.map((e) => `    [${q(e.char)}, ${q(e.name)}, ${q(e.terms)}],`).join('\n')
  return `  {\n    label: ${q(label)},\n    emoji: [\n${items}\n    ],\n  },`
}).join('\n')

const file = `// GENERATED by scripts/fetch-emoji.mjs — do not edit by hand.
// Source: emojibase (MIT) via emoji-picker-element-data.
// ${total} emoji, capped at Unicode ${MAX_UNICODE_VERSION} so nothing renders as tofu.
//
// Import this module DYNAMICALLY only (EmojiSheet does). It is a few tens of
// kB and belongs to a sheet most sessions never open; a static import would
// put it on the critical path of every page in the app.

/** [character, name, extra search terms]. Terms already in the name are dropped. */
export type EmojiEntry = readonly [char: string, name: string, terms: string]

export interface EmojiGroup {
  label: string
  emoji: EmojiEntry[]
}

export const EMOJI_GROUPS: EmojiGroup[] = [
${groupSrc}
]

export const EMOJI_COUNT = ${total}
`

writeFileSync(OUT, file)
console.log(`Wrote ${OUT}`)
console.log(`  ${total} emoji across ${GROUPS.length} groups (${skippedNew} skipped as newer than Unicode ${MAX_UNICODE_VERSION})`)
console.log(`  ${(Buffer.byteLength(file) / 1024).toFixed(1)} kB raw`)
