-- The Demo Campaign, and the people who aren't real (2026-07-26).
--
-- Two flags, and they answer two different questions.
--
-- `campaigns.is_demo` marks a campaign whose activity is GENERATED. The
-- simulator scripts refuse to touch a campaign without it, which is the whole
-- point of the column: a seeding run that can only ever hit a flagged campaign
-- cannot accidentally write thousands of invented knocks into a real one. It
-- is not a UI mode and nothing in the app branches on it yet.
--
-- `profiles.is_simulated` marks a person who is a placeholder. It is
-- deliberately NOT derived from "was created by the seeder": the leftover test
-- accounts (testguy, qa-permbreaker, conan…) are real auth rows a human made
-- by hand, and they are placeholders too — they exist so a roster has people
-- who signed up and never went out. One column, set by whoever knows the
-- answer, rather than a rule that has to keep re-deciding it.
--
-- Why on profiles rather than a side table: it is a per-person fact read on
-- every screen that renders a name, and profiles' SELECT policy is already
-- `using (true)`, so an org-readable flag costs no new policy. Contrast
-- member_phones, which lives apart precisely BECAUSE profiles is world-read.

alter table public.campaigns
  add column if not exists is_demo boolean not null default false;

comment on column public.campaigns.is_demo is
  'Activity in this campaign is generated by scripts/simulate-demo-*.mjs. The seeders refuse to write to a campaign without it.';

alter table public.profiles
  add column if not exists is_simulated boolean not null default false;

comment on column public.profiles.is_simulated is
  'This account is a placeholder, not a real person. Shown on /profile and /member/:id so nobody mistakes seeded activity for somebody''s work.';

-- Partial: the flag is a small minority of a small table, and every read is
-- "who is simulated", never "who is not".
create index if not exists profiles_simulated_idx
  on public.profiles (is_simulated) where is_simulated;

-- No policy changes. profiles SELECT is already `using (true)`; profiles
-- UPDATE is owner-or-admin and guard_profile_privileges() deliberately does
-- NOT guard this column — a demo account flipping its own placeholder badge is
-- not a privilege, and adding a branch to that trigger is real risk for none.
-- campaigns UPDATE is already is_admin().
